title: Dawid Głogowski
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://dawid-glogowski.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


# URL settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dawid-glogowski.github.io/" # the base hostname & protocol for your site


